config/routes.rb
Rails.application.routes.draw do

	root to: "artigos#index"
	resources :artigos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artigo.rb
class Artigo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artigos_controller.rb
class ArtigosController < ApplicationController
	def index
	end

	def new 
		@artigo = Artigo.new
	end

	def create
		@artigo = Artigo.new(artigo_params) 
		@artigo.save
		flash[:success] = "Artigo foi criado com sucesso." 
		redirect_to artigos_path
	end

	private
	
	def artigo_params
		params.require(:artigo).permit(:titulo, :corpo) 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/views/artigos/index.html.erb
<%= link_to "Novo Artigo", new_artigo_path %>

app/views/artigos/new.html.erb
<h3 class='text-center'>Adicionando Novo Artigo</h3>
<div class='row'>
	<div class='col-md-12'>
		<%= form_for(@artigo, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class='form-group'>
			<div class='control-label col-md-1'>
				<%= f.label :titulo %> 
			</div>
			<div class='col-md-11'>
			<%= f.text_field :titulo, class: 'form-control', placeholder: 'Título do artigo', autofocus: true %> 
			</div>
		</div>
		<div class='form-group'>
			<div class='control-label col-md-1'> 
				<%= f.label :corpo %>
			</div>
			<div class='col-md-11'>
			<%= f.text_area :corpo, rows: 10, class: 'form-control', placeholder: 'Corpo do artigo' %>
			</div> 
		</div>
		<div class='form-group'>
			<div class='col-md-offset-1 col-md-11'>
				<%= f.submit 'Criar Artigo', class: 'btn btn-primary btn-lg pull-right' %> 
			</div>
		</div> 
		<% end %>
	</div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |key, message| %> 
			<div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
				<%= message %> 
			</div>
		<% end %>
    <%= yield %>
  </body>
</html>